spring.application.name=fastfvs
spring.jpa.open-in-view=false

# 1. A URL limpa (sem a parte do user e password no final)
spring.datasource.url=jdbc:postgresql://db.chatigoixrixizrtmhfz.supabase.co:5432/postgres

# 2. O seu usuário
spring.datasource.username=postgres

# 3. A sua senha (Substitua pela senha real que você criou hoje!)
spring.datasource.password=rHdnpJKA6DrUF8gV

# 4. Configurações do Hibernate/JPA para o PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true